### ISSUE TITLE
api trả về tiến trình người dùng

### ISSUE THREAD

**Issue by minhquangdo201** [minhquangdo201/dev-research#13]
client: hiển thị những đáp án người dùng đã chọn ở lần làm trước
server: viết api sử dụng redis get lấy dữ liệu người dùng đã làm

**Comment by tanhtanh1505** [comment]
Xử lí data trong api getCache

Đầu tiên lấy dữ liệu trong redis
Sau đó map dữ liệu đó với dữ liệu câu hỏi trong database
Trả về cho người dùng format tương tự như cũ nhưng thêm trường answered là đáp án đã chọn


![image](https://user-images.githubusercontent.com/75565631/203816947-189ec557-cfc5-44bf-a873-628c511e2d7e.png)
